version: '3.3'

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - type: bind
        source: ../tools/database/schema.sql
        target: /schema.sql
      - type: bind
        source: ./osmose-menu.sql
        target: /osmose-menu.sql
      - type: bind
        source: ./postgres-init.sh
        target: /docker-entrypoint-initdb.d/postgres-init.sh
      ## To keep the data outside of container
      #- type: bind
      #  source: ./postgresql-data:
      #  target: /var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=osmose
     - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - osmose-frontend-internal

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile-api
    image: osm-fr/osmose_frontend_api
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - 20009:20009
    networks:
      - osmose-frontend-internal
      - osmose-frontend

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile-web
    image: osm-fr/osmose_frontend_web
    ports:
      - 8080:8080
    networks:
      - osmose-frontend-internal
      - osmose-frontend

networks:
  osmose-frontend-internal:
  osmose-frontend:
